create table if not exists profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text not null,
  account_xp integer not null default 0,
  account_level integer not null default 1,
  rating integer not null default 1000,
  avatar_url text,
  soft_currency integer not null default 0,
  premium_currency integer not null default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table profiles add column if not exists account_xp integer not null default 0;
alter table profiles add column if not exists account_level integer not null default 1;
alter table profiles add column if not exists rating integer not null default 1000;
alter table profiles add column if not exists avatar_url text;
alter table profiles add column if not exists soft_currency integer not null default 0;
alter table profiles add column if not exists premium_currency integer not null default 0;

alter table profiles enable row level security;

drop policy if exists "Profiles are readable by owner" on profiles;
create policy "Profiles are readable by owner"
on profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Profiles are editable by owner" on profiles;
create policy "Profiles are editable by owner"
on profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Profiles are updatable by owner" on profiles;
create policy "Profiles are updatable by owner"
on profiles for update
to authenticated
using (auth.uid() = id);

create table if not exists character_progress (
  user_id uuid references auth.users on delete cascade,
  character_id integer not null,
  level integer not null default 1,
  xp integer not null default 0,
  limit_break integer not null default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  primary key (user_id, character_id)
);

alter table character_progress add column if not exists limit_break integer not null default 0;

alter table character_progress enable row level security;

drop policy if exists "Character progress readable by owner" on character_progress;
create policy "Character progress readable by owner"
on character_progress for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Character progress insertable by owner" on character_progress;
create policy "Character progress insertable by owner"
on character_progress for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Character progress updatable by owner" on character_progress;
create policy "Character progress updatable by owner"
on character_progress for update
to authenticated
using (auth.uid() = user_id);

create table if not exists match_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  result text not null,
  turns integer,
  rating_delta integer not null default 0,
  account_xp_gain integer not null default 0,
  character_xp_gain integer not null default 0,
  created_at timestamp with time zone default now()
);

alter table match_history enable row level security;

drop policy if exists "Match history readable by owner" on match_history;
create policy "Match history readable by owner"
on match_history for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Match history insertable by owner" on match_history;
create policy "Match history insertable by owner"
on match_history for insert
to authenticated
with check (auth.uid() = user_id);

create table if not exists team_presets (
  user_id uuid references auth.users on delete cascade,
  slot integer not null,
  name text not null default '',
  character_ids integer[] not null default '{}',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  primary key (user_id, slot)
);

alter table team_presets enable row level security;

drop policy if exists "Team presets readable by owner" on team_presets;
create policy "Team presets readable by owner"
on team_presets for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Team presets insertable by owner" on team_presets;
create policy "Team presets insertable by owner"
on team_presets for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Team presets updatable by owner" on team_presets;
create policy "Team presets updatable by owner"
on team_presets for update
to authenticated
using (auth.uid() = user_id);

create table if not exists missions (
  id bigint generated by default as identity primary key,
  type text not null,
  condition text not null default 'match_any',
  condition_value text,
  title text not null,
  description text not null,
  target integer not null default 1,
  reward_soft integer not null default 0,
  reward_premium integer not null default 0,
  reward_shard_character_id integer,
  reward_shard_amount integer not null default 0,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

alter table missions add column if not exists condition text not null default 'match_any';
alter table missions add column if not exists condition_value text;

alter table missions enable row level security;

drop policy if exists "Missions readable by all" on missions;
create policy "Missions readable by all"
on missions for select
to authenticated
using (true);

create table if not exists user_missions (
  user_id uuid references auth.users on delete cascade,
  mission_id bigint references missions on delete cascade,
  progress integer not null default 0,
  claimed boolean not null default false,
  updated_at timestamp with time zone default now(),
  primary key (user_id, mission_id)
);

alter table user_missions enable row level security;

drop policy if exists "User missions readable by owner" on user_missions;
create policy "User missions readable by owner"
on user_missions for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "User missions insertable by owner" on user_missions;
create policy "User missions insertable by owner"
on user_missions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "User missions updatable by owner" on user_missions;
create policy "User missions updatable by owner"
on user_missions for update
to authenticated
using (auth.uid() = user_id);

create table if not exists user_inventory (
  user_id uuid references auth.users on delete cascade,
  character_id integer not null,
  shard_amount integer not null default 0,
  updated_at timestamp with time zone default now(),
  primary key (user_id, character_id)
);

alter table user_inventory enable row level security;

drop policy if exists "Inventory readable by owner" on user_inventory;
create policy "Inventory readable by owner"
on user_inventory for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Inventory insertable by owner" on user_inventory;
create policy "Inventory insertable by owner"
on user_inventory for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Inventory updatable by owner" on user_inventory;
create policy "Inventory updatable by owner"
on user_inventory for update
to authenticated
using (auth.uid() = user_id);

create table if not exists banners (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

alter table banners enable row level security;

drop policy if exists "Banners readable by all" on banners;
create policy "Banners readable by all"
on banners for select
to authenticated
using (true);

create table if not exists banner_items (
  id bigint generated by default as identity primary key,
  banner_id bigint references banners on delete cascade,
  item_type text not null,
  character_id integer,
  shard_amount integer not null default 0,
  soft_currency integer not null default 0,
  premium_currency integer not null default 0,
  weight integer not null default 1
);

alter table banner_items drop constraint if exists banner_items_pkey;
alter table banner_items alter column character_id drop not null;

alter table banner_items enable row level security;

drop policy if exists "Banner items readable by all" on banner_items;
create policy "Banner items readable by all"
on banner_items for select
to authenticated
using (true);

create table if not exists shop_offers (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  cost_soft integer not null default 0,
  cost_premium integer not null default 0,
  item_type text not null,
  character_id integer,
  shard_amount integer not null default 0,
  soft_currency integer not null default 0,
  premium_currency integer not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone default now()
);

alter table shop_offers enable row level security;

drop policy if exists "Shop offers readable by all" on shop_offers;
create policy "Shop offers readable by all"
on shop_offers for select
to authenticated
using (true);

-- Seed: Sukuna featured banner + shop offer
insert into banners (name, description, starts_at, ends_at)
select 'Cursed King Arrival', 'Featured: Sukuna and bonus drops.', now(), now() + interval '30 days'
where not exists (select 1 from banners where name = 'Cursed King Arrival');

with banner_cte as (
  select id from banners where name = 'Cursed King Arrival' limit 1
)
insert into banner_items (banner_id, item_type, character_id, shard_amount, soft_currency, premium_currency, weight)
select banner_cte.id, 'character', 4, 0, 0, 0, 5 from banner_cte
where not exists (
  select 1 from banner_items where banner_id = banner_cte.id and item_type = 'character' and character_id = 4
);

with banner_cte as (
  select id from banners where name = 'Cursed King Arrival' limit 1
)
insert into banner_items (banner_id, item_type, character_id, shard_amount, soft_currency, premium_currency, weight)
select banner_cte.id, 'shards', 4, 10, 0, 0, 20 from banner_cte
where not exists (
  select 1 from banner_items where banner_id = banner_cte.id and item_type = 'shards' and character_id = 4
);

with banner_cte as (
  select id from banners where name = 'Cursed King Arrival' limit 1
)
insert into banner_items (banner_id, item_type, character_id, shard_amount, soft_currency, premium_currency, weight)
select banner_cte.id, 'currency', null, 0, 200, 0, 50 from banner_cte
where not exists (
  select 1 from banner_items where banner_id = banner_cte.id and item_type = 'currency' and soft_currency = 200
);

insert into shop_offers (name, description, cost_soft, cost_premium, item_type, character_id, shard_amount, soft_currency, premium_currency, active)
select 'Sukuna Shard Pack', '10 Sukuna shards', 500, 0, 'shards', 4, 10, 0, 0, true
where not exists (select 1 from shop_offers where name = 'Sukuna Shard Pack');

-- Seed missions
insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'match_any', 'Play 5 games', 'Complete 5 matches.', 5, 200, 0
where not exists (select 1 from missions where title = 'Play 5 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'match_win', 'Win 3 games', 'Win 3 matches.', 3, 300, 0
where not exists (select 1 from missions where title = 'Win 3 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'character_level_up', 'Level up a character', 'Level up any character once.', 1, 250, 0
where not exists (select 1 from missions where title = 'Level up a character');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'weekly', 'match_any', 'Play 20 games', 'Complete 20 matches.', 20, 800, 2
where not exists (select 1 from missions where title = 'Play 20 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'weekly', 'match_win', 'Win 10 games', 'Win 10 matches.', 10, 1200, 3
where not exists (select 1 from missions where title = 'Win 10 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium, reward_shard_character_id, reward_shard_amount)
select 'limited', 'match_win', 'Event: Cursed Streak', 'Win 5 matches during the event.', 5, 1000, 5, 4, 20
where not exists (select 1 from missions where title = 'Event: Cursed Streak');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'match_any', 'Test: Play 1 Game', 'Play 1 match to earn 100 of each currency (repeatable).', 1, 100, 100
where not exists (select 1 from missions where title = 'Test: Play 1 Game');
