create table if not exists profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text not null,
  account_xp integer not null default 0,
  account_level integer not null default 1,
  rating integer not null default 1000,
  avatar_url text,
  soft_currency integer not null default 0,
  premium_currency integer not null default 0,
  role text not null default 'player',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table profiles add column if not exists account_xp integer not null default 0;
alter table profiles add column if not exists account_level integer not null default 1;
alter table profiles add column if not exists rating integer not null default 1000;
alter table profiles add column if not exists avatar_url text;
alter table profiles add column if not exists soft_currency integer not null default 0;
alter table profiles add column if not exists premium_currency integer not null default 0;
alter table profiles add column if not exists role text not null default 'player';

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from profiles
    where id = uid and role = 'admin'
  );
$$;

alter table profiles enable row level security;

drop policy if exists "Profiles are readable by owner" on profiles;
create policy "Profiles are readable by owner"
on profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Profiles are editable by owner" on profiles;
create policy "Profiles are editable by owner"
on profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Profiles are updatable by owner" on profiles;
create policy "Profiles are updatable by owner"
on profiles for update
to authenticated
using (auth.uid() = id);

-- Characters and skills
create table if not exists characters (
  id bigint generated by default as identity primary key,
  name text not null,
  rarity text not null default 'SR',
  max_hp integer not null default 80,
  max_mana integer not null default 100,
  attack integer not null default 20,
  defense integer not null default 15,
  cursed_output integer not null default 20,
  cursed_resistance integer not null default 15,
  crit_chance numeric not null default 0.05,
  portrait_url text,
  card_art_url text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists character_skills (
  id bigint generated by default as identity primary key,
  character_id bigint references characters on delete cascade,
  skill_key text not null,
  skill_type text not null,
  slot integer,
  name text not null,
  description text not null,
  payload jsonb not null default '{}'::jsonb,
  image_url text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique (character_id, skill_key)
);

alter table characters add column if not exists defense integer not null default 15;
alter table characters add column if not exists cursed_output integer not null default 20;
alter table characters add column if not exists cursed_resistance integer not null default 15;
alter table characters add column if not exists crit_chance numeric not null default 0.05;

alter table characters enable row level security;
alter table character_skills enable row level security;

drop policy if exists "Characters readable by all" on characters;
create policy "Characters readable by all"
on characters for select
to authenticated
using (true);

drop policy if exists "Character skills readable by all" on character_skills;
create policy "Character skills readable by all"
on character_skills for select
to authenticated
using (true);

create table if not exists character_progress (
  user_id uuid references auth.users on delete cascade,
  character_id integer not null,
  level integer not null default 1,
  xp integer not null default 0,
  limit_break integer not null default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  primary key (user_id, character_id)
);

alter table character_progress add column if not exists limit_break integer not null default 0;

alter table character_progress enable row level security;

drop policy if exists "Character progress readable by owner" on character_progress;
create policy "Character progress readable by owner"
on character_progress for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Character progress insertable by owner" on character_progress;
create policy "Character progress insertable by owner"
on character_progress for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Character progress updatable by owner" on character_progress;
create policy "Character progress updatable by owner"
on character_progress for update
to authenticated
using (auth.uid() = user_id);

create table if not exists match_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  result text not null,
  turns integer,
  rating_delta integer not null default 0,
  account_xp_gain integer not null default 0,
  character_xp_gain integer not null default 0,
  created_at timestamp with time zone default now()
);

alter table match_history enable row level security;

drop policy if exists "Match history readable by owner" on match_history;
create policy "Match history readable by owner"
on match_history for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Match history insertable by owner" on match_history;
create policy "Match history insertable by owner"
on match_history for insert
to authenticated
with check (auth.uid() = user_id);

create table if not exists team_presets (
  user_id uuid references auth.users on delete cascade,
  slot integer not null,
  name text not null default '',
  character_ids integer[] not null default '{}',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  primary key (user_id, slot)
);

alter table team_presets enable row level security;

drop policy if exists "Team presets readable by owner" on team_presets;
create policy "Team presets readable by owner"
on team_presets for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Team presets insertable by owner" on team_presets;
create policy "Team presets insertable by owner"
on team_presets for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Team presets updatable by owner" on team_presets;
create policy "Team presets updatable by owner"
on team_presets for update
to authenticated
using (auth.uid() = user_id);

create table if not exists missions (
  id bigint generated by default as identity primary key,
  type text not null,
  condition text not null default 'match_any',
  condition_value text,
  title text not null,
  description text not null,
  target integer not null default 1,
  reward_soft integer not null default 0,
  reward_premium integer not null default 0,
  reward_shard_character_id integer,
  reward_shard_amount integer not null default 0,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

alter table missions add column if not exists condition text not null default 'match_any';
alter table missions add column if not exists condition_value text;

alter table missions enable row level security;

drop policy if exists "Missions readable by all" on missions;
create policy "Missions readable by all"
on missions for select
to authenticated
using (true);

create table if not exists user_missions (
  user_id uuid references auth.users on delete cascade,
  mission_id bigint references missions on delete cascade,
  progress integer not null default 0,
  claimed boolean not null default false,
  updated_at timestamp with time zone default now(),
  primary key (user_id, mission_id)
);

alter table user_missions enable row level security;

drop policy if exists "User missions readable by owner" on user_missions;
create policy "User missions readable by owner"
on user_missions for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "User missions insertable by owner" on user_missions;
create policy "User missions insertable by owner"
on user_missions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "User missions updatable by owner" on user_missions;
create policy "User missions updatable by owner"
on user_missions for update
to authenticated
using (auth.uid() = user_id);

create table if not exists user_inventory (
  user_id uuid references auth.users on delete cascade,
  character_id integer not null,
  shard_amount integer not null default 0,
  updated_at timestamp with time zone default now(),
  primary key (user_id, character_id)
);

alter table user_inventory enable row level security;

drop policy if exists "Inventory readable by owner" on user_inventory;
create policy "Inventory readable by owner"
on user_inventory for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Inventory insertable by owner" on user_inventory;
create policy "Inventory insertable by owner"
on user_inventory for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Inventory updatable by owner" on user_inventory;
create policy "Inventory updatable by owner"
on user_inventory for update
to authenticated
using (auth.uid() = user_id);

create table if not exists banners (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

alter table banners enable row level security;

drop policy if exists "Banners readable by all" on banners;
create policy "Banners readable by all"
on banners for select
to authenticated
using (true);

create table if not exists banner_items (
  id bigint generated by default as identity primary key,
  banner_id bigint references banners on delete cascade,
  item_type text not null,
  character_id integer,
  shard_amount integer not null default 0,
  soft_currency integer not null default 0,
  premium_currency integer not null default 0,
  weight integer not null default 1
);

alter table banner_items drop constraint if exists banner_items_pkey;
alter table banner_items alter column character_id drop not null;

alter table banner_items enable row level security;

drop policy if exists "Banner items readable by all" on banner_items;
create policy "Banner items readable by all"
on banner_items for select
to authenticated
using (true);

create table if not exists shop_offers (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  cost_soft integer not null default 0,
  cost_premium integer not null default 0,
  item_type text not null,
  character_id integer,
  shard_amount integer not null default 0,
  soft_currency integer not null default 0,
  premium_currency integer not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone default now()
);

alter table shop_offers enable row level security;

drop policy if exists "Shop offers readable by all" on shop_offers;
create policy "Shop offers readable by all"
on shop_offers for select
to authenticated
using (true);

-- Seed characters and skills
insert into characters (id, name, rarity, max_hp, max_mana, attack)
select 1, 'Gojo', 'UR', 105, 100, 24
where not exists (select 1 from characters where id = 1);

insert into characters (id, name, rarity, max_hp, max_mana, attack)
select 2, 'Yuji', 'SSR', 95, 100, 22
where not exists (select 1 from characters where id = 2);

insert into characters (id, name, rarity, max_hp, max_mana, attack)
select 3, 'Megumi', 'SSR', 88, 100, 19
where not exists (select 1 from characters where id = 3);

insert into characters (id, name, rarity, max_hp, max_mana, attack)
select 4, 'Nobara', 'SR', 82, 100, 21
where not exists (select 1 from characters where id = 4);

insert into characters (id, name, rarity, max_hp, max_mana, attack)
select 5, 'Nanami', 'SSR', 98, 100, 25
where not exists (select 1 from characters where id = 5);

insert into characters (id, name, rarity, max_hp, max_mana, attack)
select 6, 'Jogo', 'SR', 78, 100, 20
where not exists (select 1 from characters where id = 6);

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 1, 'gojo-passive', 'passive', null, 'Six Eyes', 'Cooldowns reduce 1 turn faster, mana costs reduced by 10%',
  '{"type":"cooldown-reduction","value":1,"manaReduction":0.1}'::jsonb
where not exists (select 1 from character_skills where character_id = 1 and skill_key = 'gojo-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 1, 'gojo-1', 'ability', 1, 'Infinity', 'Become invincible for the next enemy turn',
  '{"type":"defensive","manaCost":30,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 1 and skill_key = 'gojo-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 1, 'gojo-2', 'ability', 2, 'Red - Reversal', 'Deals 34 damage to one enemy',
  '{"type":"attack","damage":34,"manaCost":25,"cooldown":2}'::jsonb
where not exists (select 1 from character_skills where character_id = 1 and skill_key = 'gojo-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 1, 'gojo-3', 'ability', 3, 'Blue - Lapse', 'Deals 22 damage and stuns for 1 turn',
  '{"type":"attack-stun","damage":22,"stunDuration":1,"manaCost":35,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 1 and skill_key = 'gojo-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 1, 'gojo-ult', 'ultimate', null, 'Hollow Purple', 'Deals 55 damage to all enemies',
  '{"type":"attack-all","damage":55,"manaCost":75,"cooldown":5}'::jsonb
where not exists (select 1 from character_skills where character_id = 1 and skill_key = 'gojo-ult');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 2, 'yuji-passive', 'passive', null, 'Vessel Body', 'Heals 6 HP at the start of each turn',
  '{"type":"regen","value":6}'::jsonb
where not exists (select 1 from character_skills where character_id = 2 and skill_key = 'yuji-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 2, 'yuji-1', 'ability', 1, 'Divergent Fist', 'Deals 30 damage to one enemy',
  '{"type":"attack","damage":30,"manaCost":20,"cooldown":2}'::jsonb
where not exists (select 1 from character_skills where character_id = 2 and skill_key = 'yuji-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 2, 'yuji-2', 'ability', 2, 'Manji Kick', 'Deals 24 damage to one enemy',
  '{"type":"attack","damage":24,"manaCost":15,"cooldown":1}'::jsonb
where not exists (select 1 from character_skills where character_id = 2 and skill_key = 'yuji-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 2, 'yuji-3', 'ability', 3, 'Adrenaline Rush', 'Boosts own attack by 14 for 2 turns',
  '{"type":"buff","buffAmount":14,"duration":2,"manaCost":30,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 2 and skill_key = 'yuji-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 2, 'yuji-ult', 'ultimate', null, 'Black Flash', 'Deals 70 damage to one enemy',
  '{"type":"attack","damage":70,"manaCost":70,"cooldown":5}'::jsonb
where not exists (select 1 from character_skills where character_id = 2 and skill_key = 'yuji-ult');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 3, 'megumi-passive', 'passive', null, 'Ten Shadows', 'All attacks deal 10% bonus damage',
  '{"type":"damage-boost","value":0.1}'::jsonb
where not exists (select 1 from character_skills where character_id = 3 and skill_key = 'megumi-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 3, 'megumi-1', 'ability', 1, 'Divine Dogs', 'Deals 24 damage to one enemy',
  '{"type":"attack","damage":24,"manaCost":20,"cooldown":1}'::jsonb
where not exists (select 1 from character_skills where character_id = 3 and skill_key = 'megumi-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 3, 'megumi-2', 'ability', 2, 'Nue', 'Deals 20 damage and stuns for 1 turn',
  '{"type":"attack-stun","damage":20,"stunDuration":1,"manaCost":35,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 3 and skill_key = 'megumi-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 3, 'megumi-3', 'ability', 3, 'Toad', 'Heals all allies for 18 HP',
  '{"type":"heal-all","healAmount":18,"manaCost":40,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 3 and skill_key = 'megumi-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 3, 'megumi-ult', 'ultimate', null, 'Chimera Shadow Garden', 'Deals 38 damage to all enemies and heals allies for 22',
  '{"type":"ultimate-megumi","damage":38,"healAmount":22,"manaCost":80,"cooldown":6}'::jsonb
where not exists (select 1 from character_skills where character_id = 3 and skill_key = 'megumi-ult');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 4, 'nobara-passive', 'passive', null, 'Resonance', 'Attacks have a 20% chance to hit twice',
  '{"type":"double-hit","value":0.2}'::jsonb
where not exists (select 1 from character_skills where character_id = 4 and skill_key = 'nobara-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 4, 'nobara-1', 'ability', 1, 'Straw Doll', 'Deals 24 damage to one enemy',
  '{"type":"attack","damage":24,"manaCost":20,"cooldown":1}'::jsonb
where not exists (select 1 from character_skills where character_id = 4 and skill_key = 'nobara-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 4, 'nobara-2', 'ability', 2, 'Hairpin', 'Deals 32 damage to one enemy',
  '{"type":"attack","damage":32,"manaCost":30,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 4 and skill_key = 'nobara-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 4, 'nobara-3', 'ability', 3, 'Resonance Link', 'Marks an enemy to take +14 damage for 2 turns',
  '{"type":"debuff-mark","extraDamage":14,"duration":2,"manaCost":35,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 4 and skill_key = 'nobara-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 4, 'nobara-ult', 'ultimate', null, 'Black Flash Hairpin', 'Deals 64 damage to one enemy',
  '{"type":"attack","damage":64,"manaCost":70,"cooldown":5}'::jsonb
where not exists (select 1 from character_skills where character_id = 4 and skill_key = 'nobara-ult');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 5, 'nanami-passive', 'passive', null, 'Ratio Technique', 'Attacks deal 20% bonus damage to enemies below 50% HP',
  '{"type":"execute","value":0.2,"threshold":0.5}'::jsonb
where not exists (select 1 from character_skills where character_id = 5 and skill_key = 'nanami-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 5, 'nanami-1', 'ability', 1, 'Blunted Blade', 'Deals 26 damage to one enemy',
  '{"type":"attack","damage":26,"manaCost":20,"cooldown":1}'::jsonb
where not exists (select 1 from character_skills where character_id = 5 and skill_key = 'nanami-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 5, 'nanami-2', 'ability', 2, 'Weak Point Strike', 'Deals 38 damage, +20 if enemy below 50% HP',
  '{"type":"attack-execute","damage":38,"bonusDamage":20,"threshold":0.5,"manaCost":35,"cooldown":2}'::jsonb
where not exists (select 1 from character_skills where character_id = 5 and skill_key = 'nanami-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 5, 'nanami-3', 'ability', 3, 'Overtime', 'Boosts own attack by 22 but takes 8 damage',
  '{"type":"buff-self-damage","buffAmount":22,"selfDamage":8,"duration":3,"manaCost":30,"cooldown":4}'::jsonb
where not exists (select 1 from character_skills where character_id = 5 and skill_key = 'nanami-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 5, 'nanami-ult', 'ultimate', null, 'Collapse', 'Deals 85 damage to one enemy',
  '{"type":"attack","damage":85,"manaCost":80,"cooldown":6}'::jsonb
where not exists (select 1 from character_skills where character_id = 5 and skill_key = 'nanami-ult');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 6, 'jogo-passive', 'passive', null, 'Disaster Flame', 'Attacks burn enemies for 6 damage at turn start',
  '{"type":"burn","value":6}'::jsonb
where not exists (select 1 from character_skills where character_id = 6 and skill_key = 'jogo-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 6, 'jogo-1', 'ability', 1, 'Ember Insects', 'Deals 20 damage to one enemy',
  '{"type":"attack","damage":20,"manaCost":15,"cooldown":1}'::jsonb
where not exists (select 1 from character_skills where character_id = 6 and skill_key = 'jogo-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 6, 'jogo-2', 'ability', 2, 'Flame Pillar', 'Deals 28 damage to one enemy',
  '{"type":"attack","damage":28,"manaCost":25,"cooldown":2}'::jsonb
where not exists (select 1 from character_skills where character_id = 6 and skill_key = 'jogo-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 6, 'jogo-3', 'ability', 3, 'Coffin of the Iron Mountain', 'Stuns one enemy for 2 turns',
  '{"type":"stun-only","stunDuration":2,"manaCost":45,"cooldown":4}'::jsonb
where not exists (select 1 from character_skills where character_id = 6 and skill_key = 'jogo-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 6, 'jogo-ult', 'ultimate', null, 'Maximum Meteor', 'Deals 62 damage to all enemies',
  '{"type":"attack-all","damage":62,"manaCost":75,"cooldown":6}'::jsonb
where not exists (select 1 from character_skills where character_id = 6 and skill_key = 'jogo-ult');

insert into characters (id, name, rarity, max_hp, max_mana, attack, defense, cursed_output, cursed_resistance, crit_chance)
select 7, 'Panda', 'SSR', 115, 100, 26, 20, 14, 18, 0.05
where not exists (select 1 from characters where id = 7);

insert into characters (id, name, rarity, max_hp, max_mana, attack, defense, cursed_output, cursed_resistance, crit_chance)
select 8, 'Toge Inumaki', 'SSR', 88, 120, 16, 15, 30, 20, 0.05
where not exists (select 1 from characters where id = 8);

insert into characters (id, name, rarity, max_hp, max_mana, attack, defense, cursed_output, cursed_resistance, crit_chance)
select 9, 'Maki Zen''in', 'SSR', 100, 80, 28, 22, 10, 16, 0.05
where not exists (select 1 from characters where id = 9);

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 7, 'panda-passive', 'passive', null, 'Gorilla Core', 'After 3 techniques, awaken Gorilla Core for 2 turns',
  '{"type":"gorilla-core"}'::jsonb
where not exists (select 1 from character_skills where character_id = 7 and skill_key = 'panda-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 7, 'panda-1', 'ability', 1, 'Drumming Beat', 'Deals 80 base damage + 120% Attack',
  '{"type":"attack","damageBase":80,"scaling":1.2,"scalingStat":"attack","damageType":"physical","coreDefenseDebuffPercent":0.2,"coreDefenseDebuffDuration":2,"manaCost":30,"cooldown":2}'::jsonb
where not exists (select 1 from character_skills where character_id = 7 and skill_key = 'panda-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 7, 'panda-2', 'ability', 2, 'Charging Tackle', 'Deals 60 base damage + 100% Attack and reinforces Defense',
  '{"type":"attack","damageBase":60,"scaling":1.0,"scalingStat":"attack","damageType":"physical","selfDefenseBuffPercent":0.15,"selfDefenseBuffDuration":2,"coreAllEnemies":true,"manaCost":40,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 7 and skill_key = 'panda-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 7, 'panda-3', 'ability', 3, 'Sister Core''s Embrace', 'Heals self for 20% HP and cleanses one affliction',
  '{"type":"heal-self","healPercent":0.2,"cleanseDebuff":true,"resetTechniqueCounter":true,"manaCost":50,"cooldown":4}'::jsonb
where not exists (select 1 from character_skills where character_id = 7 and skill_key = 'panda-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 7, 'panda-ult', 'ultimate', null, 'Unblockable Drumming Beat', 'Deals 100 base damage to all enemies (Gorilla Core required)',
  '{"type":"attack-all","damageBase":100,"scaling":1.5,"scalingStat":"attack","damageType":"physical","requiresGorillaCore":true,"coreDamageBase":150,"coreScaling":2.0,"coreBindDuration":1,"manaCost":100,"cooldown":5}'::jsonb
where not exists (select 1 from character_skills where character_id = 7 and skill_key = 'panda-ult');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 8, 'inumaki-passive', 'passive', null, 'Cursed Speech Resonance', 'Cursed Speech techniques apply Speech Mark stacks',
  '{"type":"speech-mark"}'::jsonb
where not exists (select 1 from character_skills where character_id = 8 and skill_key = 'inumaki-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 8, 'inumaki-1', 'ability', 1, 'Don''t Move', 'Deals 40 base damage + binds the target',
  '{"type":"attack-stun","damageBase":40,"scaling":0.8,"scalingStat":"cursedOutput","damageType":"cursed","bindingDuration":1,"speechMarkStacks":1,"manaCost":35,"cooldown":2}'::jsonb
where not exists (select 1 from character_skills where character_id = 8 and skill_key = 'inumaki-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 8, 'inumaki-2', 'ability', 2, 'Get Crushed', 'Deals 70 base damage + lowers Attack',
  '{"type":"attack","damageBase":70,"scaling":1.1,"scalingStat":"cursedOutput","damageType":"cursed","attackDebuffPercent":0.25,"attackDebuffDuration":2,"speechMarkStacks":1,"manaCost":45,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 8 and skill_key = 'inumaki-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 8, 'inumaki-3', 'ability', 3, 'Explode', 'Deals 50 base damage to all enemies, marks the primary target',
  '{"type":"attack-all-primary-mark","damageBase":50,"scaling":0.9,"scalingStat":"cursedOutput","damageType":"cursed","applySpeechMark":true,"manaCost":40,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 8 and skill_key = 'inumaki-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 8, 'inumaki-ult', 'ultimate', null, 'Blast Away', 'Deals 120 base damage, binds all enemies, recoil damage',
  '{"type":"attack-all","damageBase":120,"scaling":1.8,"scalingStat":"cursedOutput","damageType":"cursed","bindingAllDuration":1,"speechMarkAllStacks":2,"recoilPercent":0.1,"manaCost":120,"cooldown":6}'::jsonb
where not exists (select 1 from character_skills where character_id = 8 and skill_key = 'inumaki-ult');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 9, 'maki-passive', 'passive', null, 'Heavenly Restriction', 'No natural cursed energy regen, +20% crit chance',
  '{"type":"heavenly-restriction","critBonus":0.2}'::jsonb
where not exists (select 1 from character_skills where character_id = 9 and skill_key = 'maki-passive');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 9, 'maki-1', 'ability', 1, 'Cursed Tool Flurry', 'Deals 50 base damage + 100% Attack',
  '{"type":"attack","damageBase":50,"scaling":1.0,"scalingStat":"attack","damageType":"physical","isBasic":true,"onCritCooldownReduction":true,"manaCost":25,"cooldown":1}'::jsonb
where not exists (select 1 from character_skills where character_id = 9 and skill_key = 'maki-1');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 9, 'maki-2', 'ability', 2, 'Precision Thrust', 'Deals 90 base damage + 140% Attack with guaranteed crit',
  '{"type":"attack","damageBase":90,"scaling":1.4,"scalingStat":"attack","damageType":"physical","guaranteedCrit":true,"damageAmp":0.15,"damageAmpDuration":2,"manaCost":40,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 9 and skill_key = 'maki-2');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 9, 'maki-3', 'ability', 3, 'Weapon Arsenal', 'Deals 40 base damage to 2 random enemies',
  '{"type":"attack-random","damageBase":40,"scaling":0.8,"scalingStat":"attack","damageType":"physical","targetCount":2,"selfAttackBuffPercent":0.3,"selfAttackBuffDuration":3,"setNextBasicDouble":true,"manaCost":35,"cooldown":3}'::jsonb
where not exists (select 1 from character_skills where character_id = 9 and skill_key = 'maki-3');

insert into character_skills (character_id, skill_key, skill_type, slot, name, description, payload)
select 9, 'maki-ult', 'ultimate', null, 'Three-Section Staff Maelstrom', 'Deals 110 base damage to all enemies and restores cursed energy',
  '{"type":"attack-all","damageBase":110,"scaling":1.7,"scalingStat":"attack","damageType":"physical","energyRestorePerHit":15,"grantFlowStateTurns":3,"manaCost":80,"cooldown":5}'::jsonb
where not exists (select 1 from character_skills where character_id = 9 and skill_key = 'maki-ult');

-- Seed: Sukuna featured banner + shop offer
insert into banners (name, description, starts_at, ends_at)
select 'Cursed King Arrival', 'Featured: Sukuna and bonus drops.', now(), now() + interval '30 days'
where not exists (select 1 from banners where name = 'Cursed King Arrival');

with banner_cte as (
  select id from banners where name = 'Cursed King Arrival' limit 1
)
insert into banner_items (banner_id, item_type, character_id, shard_amount, soft_currency, premium_currency, weight)
select banner_cte.id, 'character', 4, 0, 0, 0, 5 from banner_cte
where not exists (
  select 1 from banner_items where banner_id = banner_cte.id and item_type = 'character' and character_id = 4
);

with banner_cte as (
  select id from banners where name = 'Cursed King Arrival' limit 1
)
insert into banner_items (banner_id, item_type, character_id, shard_amount, soft_currency, premium_currency, weight)
select banner_cte.id, 'shards', 4, 10, 0, 0, 20 from banner_cte
where not exists (
  select 1 from banner_items where banner_id = banner_cte.id and item_type = 'shards' and character_id = 4
);

with banner_cte as (
  select id from banners where name = 'Cursed King Arrival' limit 1
)
insert into banner_items (banner_id, item_type, character_id, shard_amount, soft_currency, premium_currency, weight)
select banner_cte.id, 'currency', null, 0, 200, 0, 50 from banner_cte
where not exists (
  select 1 from banner_items where banner_id = banner_cte.id and item_type = 'currency' and soft_currency = 200
);

insert into shop_offers (name, description, cost_soft, cost_premium, item_type, character_id, shard_amount, soft_currency, premium_currency, active)
select 'Sukuna Shard Pack', '10 Sukuna shards', 500, 0, 'shards', 4, 10, 0, 0, true
where not exists (select 1 from shop_offers where name = 'Sukuna Shard Pack');

-- Seed missions
insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'match_any', 'Play 5 games', 'Complete 5 matches.', 5, 200, 0
where not exists (select 1 from missions where title = 'Play 5 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'match_win', 'Win 3 games', 'Win 3 matches.', 3, 300, 0
where not exists (select 1 from missions where title = 'Win 3 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'character_level_up', 'Level up a character', 'Level up any character once.', 1, 250, 0
where not exists (select 1 from missions where title = 'Level up a character');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'weekly', 'match_any', 'Play 20 games', 'Complete 20 matches.', 20, 800, 2
where not exists (select 1 from missions where title = 'Play 20 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'weekly', 'match_win', 'Win 10 games', 'Win 10 matches.', 10, 1200, 3
where not exists (select 1 from missions where title = 'Win 10 games');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium, reward_shard_character_id, reward_shard_amount)
select 'limited', 'match_win', 'Event: Cursed Streak', 'Win 5 matches during the event.', 5, 1000, 5, 4, 20
where not exists (select 1 from missions where title = 'Event: Cursed Streak');

insert into missions (type, condition, title, description, target, reward_soft, reward_premium)
select 'daily', 'match_any', 'Test: Play 1 Game', 'Play 1 match to earn 100 of each currency (repeatable).', 1, 100, 100
where not exists (select 1 from missions where title = 'Test: Play 1 Game');

-- PvP matchmaking
create table if not exists pvp_queue (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  mode text not null,
  team_ids integer[] not null default '{}',
  team_state jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

alter table pvp_queue enable row level security;

drop policy if exists "PVP queue readable by all" on pvp_queue;
create policy "PVP queue readable by all"
on pvp_queue for select
to authenticated
using (true);

drop policy if exists "PVP queue insertable by owner" on pvp_queue;
create policy "PVP queue insertable by owner"
on pvp_queue for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "PVP queue deletable by owner" on pvp_queue;
create policy "PVP queue deletable by owner"
on pvp_queue for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists pvp_matches (
  id uuid primary key default gen_random_uuid(),
  mode text not null,
  player1_id uuid references auth.users on delete set null,
  player2_id uuid references auth.users on delete set null,
  player1_team integer[] not null default '{}',
  player2_team integer[] not null default '{}',
  state jsonb not null default '{}'::jsonb,
  turn integer not null default 1,
  turn_owner uuid,
  status text not null default 'active',
  winner_id uuid,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table pvp_matches enable row level security;

drop policy if exists "PVP matches readable by players" on pvp_matches;
create policy "PVP matches readable by players"
on pvp_matches for select
to authenticated
using (auth.uid() = player1_id or auth.uid() = player2_id);

drop policy if exists "PVP matches insertable by players" on pvp_matches;
create policy "PVP matches insertable by players"
on pvp_matches for insert
to authenticated
with check (auth.uid() = player1_id or auth.uid() = player2_id);

drop policy if exists "PVP matches updatable by players" on pvp_matches;
create policy "PVP matches updatable by players"
on pvp_matches for update
to authenticated
using (auth.uid() = player1_id or auth.uid() = player2_id);

create table if not exists pvp_turns (
  id bigint generated by default as identity primary key,
  match_id uuid references pvp_matches on delete cascade,
  user_id uuid references auth.users on delete cascade,
  turn_number integer not null,
  actions jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

alter table pvp_turns enable row level security;

drop policy if exists "PVP turns readable by players" on pvp_turns;
create policy "PVP turns readable by players"
on pvp_turns for select
to authenticated
using (
  exists (
    select 1 from pvp_matches
    where pvp_matches.id = match_id
      and (auth.uid() = pvp_matches.player1_id or auth.uid() = pvp_matches.player2_id)
  )
);

drop policy if exists "PVP turns insertable by owner" on pvp_turns;
create policy "PVP turns insertable by owner"
on pvp_turns for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from pvp_matches
    where pvp_matches.id = match_id
      and (auth.uid() = pvp_matches.player1_id or auth.uid() = pvp_matches.player2_id)
  )
);

create table if not exists story_progress (
  user_id uuid references auth.users on delete cascade,
  chapter_id text not null,
  active_node_id text,
  completed_nodes jsonb not null default '[]'::jsonb,
  rewards_claimed boolean not null default false,
  updated_at timestamp with time zone default now(),
  primary key (user_id, chapter_id)
);

alter table story_progress enable row level security;

drop policy if exists "Story progress readable by owner" on story_progress;
create policy "Story progress readable by owner"
on story_progress for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Story progress insertable by owner" on story_progress;
create policy "Story progress insertable by owner"
on story_progress for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Story progress updatable by owner" on story_progress;
create policy "Story progress updatable by owner"
on story_progress for update
to authenticated
using (auth.uid() = user_id);

create table if not exists user_items (
  user_id uuid references auth.users on delete cascade,
  item_id text not null,
  quantity integer not null default 0,
  updated_at timestamp with time zone default now(),
  primary key (user_id, item_id)
);

alter table user_items enable row level security;

drop policy if exists "Items readable by owner" on user_items;
create policy "Items readable by owner"
on user_items for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Items insertable by owner" on user_items;
create policy "Items insertable by owner"
on user_items for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Items updatable by owner" on user_items;
create policy "Items updatable by owner"
on user_items for update
to authenticated
using (auth.uid() = user_id);

create table if not exists user_titles (
  user_id uuid references auth.users on delete cascade,
  title_id text not null,
  unlocked boolean not null default true,
  active boolean not null default false,
  updated_at timestamp with time zone default now(),
  primary key (user_id, title_id)
);

alter table user_titles enable row level security;

drop policy if exists "Titles readable by owner" on user_titles;
create policy "Titles readable by owner"
on user_titles for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Titles insertable by owner" on user_titles;
create policy "Titles insertable by owner"
on user_titles for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Titles updatable by owner" on user_titles;
create policy "Titles updatable by owner"
on user_titles for update
to authenticated
using (auth.uid() = user_id);

-- Admin access policies
drop policy if exists "Admin full access to profiles" on profiles;
create policy "Admin full access to profiles"
on profiles for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to characters" on characters;
create policy "Admin full access to characters"
on characters for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to character skills" on character_skills;
create policy "Admin full access to character skills"
on character_skills for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to character progress" on character_progress;
create policy "Admin full access to character progress"
on character_progress for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to match history" on match_history;
create policy "Admin full access to match history"
on match_history for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to team presets" on team_presets;
create policy "Admin full access to team presets"
on team_presets for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to missions" on missions;
create policy "Admin full access to missions"
on missions for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to user missions" on user_missions;
create policy "Admin full access to user missions"
on user_missions for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to user inventory" on user_inventory;
create policy "Admin full access to user inventory"
on user_inventory for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to banners" on banners;
create policy "Admin full access to banners"
on banners for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to banner items" on banner_items;
create policy "Admin full access to banner items"
on banner_items for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to shop offers" on shop_offers;
create policy "Admin full access to shop offers"
on shop_offers for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to story progress" on story_progress;
create policy "Admin full access to story progress"
on story_progress for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to user items" on user_items;
create policy "Admin full access to user items"
on user_items for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to user titles" on user_titles;
create policy "Admin full access to user titles"
on user_titles for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to pvp queue" on pvp_queue;
create policy "Admin full access to pvp queue"
on pvp_queue for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to pvp matches" on pvp_matches;
create policy "Admin full access to pvp matches"
on pvp_matches for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));

drop policy if exists "Admin full access to pvp turns" on pvp_turns;
create policy "Admin full access to pvp turns"
on pvp_turns for all
to authenticated
using (is_admin(auth.uid()))
with check (is_admin(auth.uid()));
