import { definePassive, defendSkill } from '@/features/battle/content.ts'
import { fighter, skill, modifierEffect } from './_helpers.ts'

export const hanami = fighter({
  id: 'hanami',
  name: 'Hanami',
  shortName: 'Hanami',
  rarity: 'SSR',
  role: 'Control / Sustain',
  portraitFrame: { scale: 2.0, y: '-10%' },
  maxHp: 100,
  passiveEffects: [
    definePassive({
      id: 'hanami-natural-body',
      trigger: 'onRoundStart',
      effects: [
        { type: 'shield', amount: 10, label: 'Natural Body', tags: ['natural-body'], target: 'self' },
        modifierEffect('Natural Body Defense', 'damageTaken', -5, 1, 'self', ['natural-body-defense']),
      ],
      label: 'Natural Body',
      description: 'At the start of each turn, Hanami gains 10 destructible defense that refreshes. While Hanami has this destructible defense, they take 5 less damage from all sources.',
      icon: { label: 'NB', tone: 'teal' },
    }),
  ],
  abilities: [
    skill({
      id: 'hanami-root-snare',
      name: 'Root Snare',
      description: 'This skill targets one enemy, dealing 15 damage to them. For 1 turn, the target will deal 15 less damage and cannot reduce or prevent damage.',
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Ranged', 'Instant'],
      cooldown: 1,
      energyCost: { random: 1 },
      power: 15,
      effects: [
        { type: 'damage', power: 15, target: 'inherit' },
        modifierEffect('Root Snare', 'damageDealt', -15, 1, 'inherit', ['root-snare']),
        modifierEffect('Root Snare', 'canReduceDamageTaken', false, 1, 'inherit', ['root-snare']),
      ],
    }),
    skill({
      id: 'hanami-cursed-bud-growth',
      name: 'Cursed Bud Growth',
      description: 'This skill targets one enemy, dealing 20 damage to them. The next time that enemy uses a skill, they will take 15 damage. If this effect triggers, Hanami will heal 15 health.',
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Ranged', 'Instant'],
      cooldown: 2,
      energyCost: { random: 2 },
      power: 20,
      effects: [
        { type: 'damage', power: 20, target: 'inherit' },
        {
          type: 'reaction',
          label: 'Cursed Bud Growth',
          trigger: 'onAbilityUse',
          duration: 1,
          harmfulOnly: false,
          consumeOnTrigger: true,
          target: 'inherit',
          effects: [
            { type: 'damage', power: 15, target: 'inherit' },
            { type: 'heal', power: 15, target: 'self' },
          ],
        },
      ],
    }),
    skill({
      id: 'hanami-forest-expansion',
      name: 'Forest Expansion',
      description: 'This skill deals 15 damage to all enemies. For 2 turns, enemies will take 5 additional damage from all sources and deal 5 less damage.',
      kind: 'attack',
      targetRule: 'enemy-all',
      classes: ['Physical', 'Ranged', 'Instant'],
      cooldown: 3,
      energyCost: { random: 1, mental: 1 },
      power: 15,
      effects: [
        { type: 'damage', power: 15, target: 'all-enemies' },
        modifierEffect('Forest Expansion', 'damageTaken', 5, 2, 'all-enemies', ['forest-expansion']),
        modifierEffect('Forest Expansion', 'damageDealt', -5, 2, 'all-enemies', ['forest-expansion']),
      ],
    }),
  ],
  ultimate: defendSkill({
    id: 'hanami-natures-resilience',
    name: "Nature's Resilience",
    description: "This skill makes Hanami invulnerable for 1 turn. During this turn, each time Hanami is targeted by a harmful skill, all enemies will take 10 damage.",
    targetRule: 'self',
    classes: ['Strategic', 'Instant', 'Ultimate'],
    cooldown: 4,
    duration: 1,
    energyCost: { mental: 1 },
    effects: [
      { type: 'invulnerable', duration: 1, target: 'self' },
      {
        type: 'reaction',
        label: "Nature's Resilience",
        trigger: 'onBeingTargeted',
        duration: 1,
        harmfulOnly: true,
        consumeOnTrigger: false,
        target: 'self',
        effects: [{ type: 'damage', power: 10, target: 'all-enemies' }],
      },
    ],
  }),
})
