import { definePassive, defendSkill } from '@/features/battle/content.ts'
import { fighter, modifierEffect, skill } from './_helpers.ts'

export const megumi = fighter({
  id: 'megumi',
  name: 'Megumi Fushiguro',
  shortName: 'Megumi',
  rarity: 'SSR',
  role: 'Utility / Control / Survival',
  portraitFrame: { scale: 2.14, y: '-14%' },
  maxHp: 100,
  passiveEffects: [
    definePassive({
      id: 'megumi-ten-shadows-strategist',
      trigger: 'onTakeDamage',
      effects: [modifierEffect('Ten Shadows Counterpressure', 'damageDealt', 10, 1, 'self', ['ten-shadows-counterpressure'])],
      label: 'Ten Shadows Strategist',
      description: 'When Megumi takes damage, his skills deal 10 additional damage for 1 turn.',
      icon: { label: 'TS', tone: 'teal' },
    }),
  ],
  abilities: [
    skill({
      id: 'megumi-dogs',
      name: 'Demon Dogs: Hunt',
      description: 'This skill deals 20 damage to one enemy. For 1 turn, they cannot reduce damage or become invulnerable. Megumi gains 1 Shikigami stack.',
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Melee', 'Instant'],
      cooldown: 0,
      energyCost: { technique: 1 },
      power: 20,
      effects: [
        { type: 'damage', power: 20, target: 'inherit' },
        modifierEffect('Demon Dogs: Hunt', 'canReduceDamageTaken', false, 1, 'inherit', ['demon-dogs-hunt']),
        modifierEffect('Demon Dogs: Hunt', 'canGainInvulnerable', false, 1, 'inherit', ['demon-dogs-hunt']),
        { type: 'adjustCounter', key: 'shikigami', amount: 1, target: 'self' },
      ],
    }),
    skill({
      id: 'megumi-nue',
      name: 'Nue: Flank',
      description: 'This skill deals 25 piercing damage to one enemy. Megumi gains 1 Shikigami stack.',
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Special', 'Ranged', 'Instant'],
      cooldown: 0,
      energyCost: { vow: 1 },
      power: 25,
      effects: [
        { type: 'damage', power: 25, piercing: true, target: 'inherit' },
        { type: 'adjustCounter', key: 'shikigami', amount: 1, target: 'self' },
      ],
    }),
    skill({
      id: 'megumi-shadow-recall',
      name: 'Shikigami Recall',
      description: 'Megumi removes all Shikigami stacks and recovers 5 health and 5 shield per stack consumed.',
      kind: 'heal',
      targetRule: 'self',
      classes: ['Strategic', 'Instant'],
      cooldown: 1,
      energyCost: { random: 1 },
      effects: [
        { type: 'healScaledByCounter', counterKey: 'shikigami', counterSource: 'actor', powerPerStack: 5, consumeStacks: false, target: 'self' },
        { type: 'shieldScaledByCounter', counterKey: 'shikigami', counterSource: 'actor', powerPerStack: 5, shieldLabel: 'Shikigami Recall', shieldTags: ['shikigami-recall'], consumeStacks: true, target: 'self' },
      ],
    }),
  ],
  ultimate: defendSkill({
    id: 'megumi-toad',
    name: 'Toad: Rescue',
    description: 'This skill makes Megumi Fushiguro or one ally invulnerable for 1 turn.',
    targetRule: 'ally-single',
    classes: ['Strategic', 'Instant', 'Ultimate'],
    cooldown: 4,
    duration: 1,
    energyCost: { random: 1 },
  }),
})
