import { definePassive, defendSkill } from '@/features/battle/content.ts'
import { fighter, skill, markerEffect, modifierEffect } from './_helpers.ts'

export const momo = fighter({
  id: 'momo',
  name: 'Momo Nishimiya',
  shortName: 'Momo',
  rarity: 'R',
  role: 'Aerial Support',
  portraitFrame: { scale: 2, y: '-10%' },
  maxHp: 100,
  passiveEffects: [
    definePassive({
      id: 'momo-battlefield-awareness',
      trigger: 'onRoundStart',
      conditions: [{ type: 'counterAtLeast', key: '__never_momo_display_only', value: 1 }],
      effects: [markerEffect('Battlefield Awareness', 'permanent', 'self', ['battlefield-awareness'])],
      label: 'Battlefield Awareness',
      description: 'Momo monitors the battlefield from above, coordinating with allies and tracking enemy positions.',
      icon: { label: 'BA', tone: 'teal' },
    }),
  ],
  abilities: [
    skill({
      id: 'momo-aerial-support',
      name: 'Aerial Support',
      description: 'One ally deals 10 additional damage and their skills cost 1 less random Energy for 2 turns.',
      kind: 'utility',
      targetRule: 'ally-single',
      classes: ['Strategic', 'Instant'],
      cooldown: 2,
      energyCost: { random: 1 },
      effects: [
        modifierEffect('Aerial Support', 'damageDealt', 10, 2, 'inherit', ['aerial-support'], { intent: 'helpful' }),
        { type: 'modifyAbilityCost', target: 'inherit', modifier: { mode: 'reduceRandom', amount: 1, duration: 2, label: 'Aerial Support' } },
      ],
    }),
    skill({
      id: 'momo-disrupting-gust',
      name: 'Disrupting Gust',
      description: 'Deals 10 damage. For 1 turn, the target deals 10 less damage and their next skill costs 1 more random energy.',
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Ranged', 'Instant'],
      cooldown: 1,
      energyCost: { mental: 1 },
      power: 10,
      effects: [
        { type: 'damage', power: 10, target: 'inherit' },
        modifierEffect('Disrupting Gust', 'damageDealt', -10, 1, 'inherit', ['disrupting-gust'], { intent: 'harmful' }),
        { type: 'modifyAbilityCost', target: 'inherit', modifier: { mode: 'increaseRandom', amount: 1, duration: 1, uses: 1, label: 'Disrupting Gust' } },
      ],
    }),
    skill({
      id: 'momo-coordinated-assault',
      name: 'Coordinated Assault',
      description: 'For 1 turn, the next time the target takes damage, they take 15 additional damage. If the target is affected by Disrupting Gust, they take 15 damage immediately instead.',
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Ranged', 'Instant'],
      cooldown: 2,
      energyCost: { random: 1 },
      power: 15,
      effects: [
        {
          target: 'inherit',
          type: 'conditional',
          conditions: [{ type: 'targetHasModifierTag', tag: 'disrupting-gust' }],
          effects: [{ type: 'damage', power: 15, target: 'inherit' }],
          elseEffects: [{
            type: 'reaction',
            label: 'Coordinated Assault',
            trigger: 'onDamageApplied',
            duration: 1,
            intent: 'harmful',
            consumeOnTrigger: true,
            target: 'inherit',
            effects: [{ type: 'damage', power: 15, target: 'inherit' }],
          }],
        },
      ],
    }),
  ],
  ultimate: defendSkill({
    id: 'momo-evasive-flight',
    name: 'Evasive Flight',
    description: 'Momo becomes invulnerable for 1 turn. During that turn, her team takes 5 less damage.',
    targetRule: 'self',
    classes: ['Strategic', 'Instant', 'Ultimate'],
    cooldown: 4,
    duration: 1,
    energyCost: { random: 1 },
    effects: [
      { type: 'invulnerable', duration: 1, target: 'self' },
      modifierEffect('Evasive Flight', 'damageTaken', -5, 1, 'all-allies', ['evasive-flight'], { intent: 'helpful' }),
    ],
  }),
})
