import { definePassive, defendSkill } from '@/features/battle/content.ts'
import { fighter, skill, modifierEffect, markerEffect } from './_helpers.ts'

export const nobara = fighter({
  id: 'nobara',
  name: 'Nobara Kugisaki',
  shortName: 'Nobara',
  rarity: 'SR',
  role: 'Debuff / Punish',
  portraitFrame: { scale: 2.08, y: '-10%' },
  maxHp: 100,
  initialStateCounters: { straw_doll_ritual_stacks: 0 },
  passiveEffects: [
    definePassive({
      id: 'nobara-straw-doll-ritual-loop',
      trigger: 'onRoundStart',
      conditions: [{ type: 'fighterFlag', key: 'straw_doll_ritual_active', value: true }],
      effects: [
        { type: 'damageScaledByCounter', counterKey: 'straw_doll_ritual_stacks', counterSource: 'actor', powerPerStack: 5, consumeStacks: false, target: 'all-enemies' },
        { type: 'shield', amount: 5, label: 'Straw Doll Guard', tags: ['straw-doll-ritual'], target: 'self' },
      ],
      label: 'Straw Doll Ritual Loop',
      hidden: true,
    }),
    definePassive({
      id: 'nobara-hairpin-opening',
      trigger: 'onBeingTargeted',
      conditions: [{ type: 'fighterFlag', key: 'straw_doll_ritual_active', value: true }],
      effects: [
        {
          type: 'addModifier',
          target: 'attacker',
          modifier: {
            label: 'Hairpin Opening',
            stat: 'cooldownTick',
            mode: 'flat',
            value: 0,
            duration: { kind: 'rounds', rounds: 1 },
            tags: ['nobara-hairpin-targetable'],
            visible: true,
            stacking: 'replace',
          },
        },
      ],
      label: 'Hairpin Opening',
      hidden: true,
    }),
    definePassive({
      id: 'nobara-straw-effigy',
      trigger: 'onDealDamage',
      effects: [
        {
          type: 'reaction',
          target: 'inherit',
          label: 'Straw Effigy',
          trigger: 'onAbilityUse',
          duration: 1,
          harmfulOnly: false,
          consumeOnTrigger: false,
          oncePerRound: false,
          effects: [{ type: 'damage', power: 5, target: 'inherit' }],
        },
      ],
      label: 'Straw Effigy',
      description: 'Whenever an enemy takes damage from Nobara\'s skills, they gain Straw Effigy for 1 turn. If an enemy with Straw Effigy uses a skill, they will receive 5 damage.',
      icon: { label: 'SE', tone: 'red' },
    }),
  ],
  abilities: [
    skill({
      id: 'nobara-straw-doll-ritual',
      name: 'Straw Doll Ritual',
      description: 'Each turn, for the rest of the game, all enemies will receive 5 damage and will be healed 5 less health. Nobara will gain 5 destructible defense. This skill stacks. While this skill is active, any enemy who uses a skill on Nobara can be targeted by Hairpin for 1 turn.',
      kind: 'utility',
      targetRule: 'self',
      classes: ['Special', 'Ranged', 'Instant'],
      cooldown: 4,
      energyCost: { technique: 1, mental: 1 },
      effects: [
        { type: 'setFlag', key: 'straw_doll_ritual_active', value: true, target: 'self' },
        { type: 'adjustCounter', key: 'straw_doll_ritual_stacks', amount: 1, target: 'self' },
        {
          type: 'addModifier',
          target: 'all-enemies',
          modifier: {
            label: 'Straw Doll Ritual',
            stat: 'healTaken',
            mode: 'flat',
            value: -5,
            duration: { kind: 'permanent' },
            tags: ['straw-doll-ritual'],
            visible: true,
            stacking: 'replace',
          },
        },
      ],
    }),
    skill({
      id: 'nobara-hammer-and-nails',
      name: 'Hammer & Nails',
      description: 'This skill targets one enemy, dealing 20 damage to them. For the next two turns, they will receive an additional 5 damage from Straw Doll Ritual. During this time, Hairpin can be used on them.',
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Ranged', 'Instant'],
      cooldown: 1,
      energyCost: { physical: 1 },
      power: 20,
      effects: [
        { type: 'damage', power: 20, target: 'inherit' },
        {
          type: 'addModifier',
          target: 'inherit',
          modifier: {
            label: 'Hammer & Nails',
            stat: 'damageTaken',
            mode: 'flat',
            value: 5,
            duration: { kind: 'rounds', rounds: 2 },
            tags: ['straw-doll-ritual', 'nobara-hairpin-targetable'],
            visible: true,
            stacking: 'replace',
          },
        },
      ],
    }),
    skill({
      id: 'nobara-hairpin',
      name: 'Hairpin',
      description: 'This skill deals 15 damage to all applicable enemies and increases the damage they receive from Straw Doll Ritual permanently by 5.',
      kind: 'attack',
      targetRule: 'enemy-all',
      classes: ['Physical', 'Ranged', 'Instant'],
      cooldown: 1,
      energyCost: {},
      power: 15,
      effects: [
        { type: 'damageFiltered', power: 15, requiresTag: 'nobara-hairpin-targetable', target: 'all-enemies' },
        {
          type: 'conditional',
          target: 'inherit',
          conditions: [{ type: 'targetHasModifierTag', tag: 'nobara-hairpin-targetable' }],
          effects: [{ type: 'adjustCounter', key: 'straw_doll_ritual_stacks', amount: 1, target: 'self' }],
        },
      ],
    }),
  ],
  ultimate: defendSkill({
    id: 'nobara-straw-doll-decoy',
    name: 'Straw Doll Decoy',
    description: 'This skill makes Nobara invulnerable for 1 turn.',
    targetRule: 'self',
    classes: ['Strategic', 'Instant', 'Ultimate'],
    cooldown: 4,
    duration: 1,
    energyCost: { mental: 1 },
  }),
})
