import { definePassive, defendSkill } from '@/features/battle/content.ts'
import { fighter, skill } from './_helpers.ts'

export const yuji = fighter({
  id: 'yuji',
  name: 'Yuji Itadori',
  shortName: 'Yuji',
  rarity: 'SSR',
  role: 'Striker / Transformation',
  portraitFrame: { scale: 2.06, y: '-10%' },
  maxHp: 100,
  passiveEffects: [
    definePassive({
      id: 'yuji-sukuna-vessel',
      trigger: 'onTakeDamage',
      conditions: [
        { type: 'selfHpBelow', threshold: 0.1 },
        { type: 'fighterFlag', key: 'sukuna_vessel_used', value: false },
      ],
      effects: [
        { type: 'setFlag', key: 'sukuna_vessel_used', value: true, target: 'self' },
        { type: 'setHpFromCounter', base: 10, counterKey: 'sukuna_bonus_hp', target: 'self' },
        {
          type: 'addModifier',
          target: 'self',
          modifier: {
            label: 'Sukuna Manifested',
            stat: 'isUndying',
            mode: 'set',
            value: true,
            duration: { kind: 'rounds', rounds: 1 },
            tags: ['sukuna-vessel'],
            visible: true,
            stacking: 'replace',
          },
        },
        {
          type: 'replaceAbilities',
          target: 'self',
          replacements: [
            {
              slotAbilityId: 'yuji-divergent-fist',
              duration: 1,
              ability: skill({
                id: 'yuji-sukuna-cleave',
                name: 'Sukuna: Cleave',
                description: 'Sukuna tears through one enemy for overwhelming damage.',
                kind: 'attack',
                targetRule: 'enemy-single',
                classes: ['Melee', 'Physical', 'Instant'],
                cooldown: 0,
                energyCost: {},
                power: 45,
                effects: [{ type: 'damage', power: 45, target: 'inherit', cannotBeCountered: true, cannotBeReflected: true }],
                cannotBeCountered: true,
                cannotBeReflected: true,
              }),
            },
            {
              slotAbilityId: 'yuji-cursed-rush',
              duration: 1,
              ability: skill({
                id: 'yuji-sukuna-dismantle',
                name: 'Sukuna: Dismantle',
                description: 'Sukuna cuts across every enemy.',
                kind: 'attack',
                targetRule: 'enemy-all',
                classes: ['Ranged', 'Physical', 'Instant'],
                cooldown: 0,
                energyCost: {},
                power: 30,
                effects: [{ type: 'damage', power: 30, target: 'all-enemies', cannotBeCountered: true, cannotBeReflected: true }],
                cannotBeCountered: true,
                cannotBeReflected: true,
              }),
            },
            {
              slotAbilityId: 'yuji-black-flash',
              duration: 1,
              ability: skill({
                id: 'yuji-sukuna-domain-cut',
                name: 'Sukuna: Domain Cut',
                description: 'Sukuna finishes one enemy with a decisive slash.',
                kind: 'attack',
                targetRule: 'enemy-single',
                classes: ['Melee', 'Physical', 'Instant'],
                cooldown: 0,
                energyCost: {},
                power: 60,
                effects: [{ type: 'damage', power: 60, target: 'inherit', cannotBeCountered: true, cannotBeReflected: true }],
                cannotBeCountered: true,
                cannotBeReflected: true,
              }),
            },
          ],
        },
      ],
      label: "Sukuna's Vessel",
      description: "When Yuji's health drops below 10 for the first time, this passive ability will activate. Yuji will transform into Sukuna for one turn; this transformation cannot be ignored. While transformed, Yuji becomes unable to die. When this transformation ends, Yuji's health will be set to 10 plus all accumulated bonuses from his skills. This transformation can only occur once.",
      icon: { label: 'SV', tone: 'red' },
      counterKey: 'sukuna_bonus_hp',
    }),
  ],
  abilities: [
    skill({
      id: 'yuji-divergent-fist',
      name: 'Divergent Fist',
      description: "This skill targets one enemy, dealing 25 damage to them and increasing the health Yuji gains after Sukuna's transformation by 5; this effect stacks.",
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Melee', 'Instant'],
      cooldown: 1,
      energyCost: { random: 1 },
      power: 25,
      effects: [
        { type: 'damage', power: 25, target: 'inherit' },
        { type: 'adjustCounter', key: 'sukuna_bonus_hp', amount: 5, target: 'self' },
      ],
    }),
    skill({
      id: 'yuji-cursed-rush',
      name: 'Cursed Rush',
      description: "This skill deals 10 damage to one random enemy each turn for 3 turns. If an enemy is struck twice by this skill from a single use, it will deal 5 more damage to them. Each time this skill damages a new enemy, the health Yuji gains after Sukuna's transformation will be increased by 5 permanently; this effect stacks.",
      kind: 'attack',
      targetRule: 'self',
      classes: ['Physical', 'Melee', 'Action'],
      cooldown: 3,
      energyCost: { vow: 2 },
      effects: [{ type: 'randomEnemyDamageOverTime', power: 10, duration: 3, historyKey: 'cursed-rush', repeatPowerBonus: 5, newTargetCounterKey: 'sukuna_bonus_hp', newTargetCounterAmount: 5, target: 'self' }],
    }),
    skill({
      id: 'yuji-black-flash',
      name: 'Black Flash',
      description: "This skill targets one enemy dealing 20 damage to them and 5 to all other enemies. For one turn, if the main target of this skill uses a new harmful skill, the health Yuji gains after Sukuna's transformation will be increased by 5; this effect stacks.",
      kind: 'attack',
      targetRule: 'enemy-single',
      classes: ['Physical', 'Melee', 'Instant'],
      cooldown: 0,
      energyCost: { vow: 1, mental: 1 },
      power: 20,
      effects: [
        { type: 'damage', power: 20, target: 'inherit' },
        { type: 'damage', power: 5, target: 'other-enemies' },
        {
          type: 'reaction',
          target: 'inherit',
          label: 'Black Flash Pressure',
          trigger: 'onAbilityUse',
          duration: 1,
          harmfulOnly: true,
          consumeOnTrigger: true,
          effects: [{ type: 'adjustCounter', key: 'sukuna_bonus_hp', amount: 5, target: 'self' }],
        },
      ],
    }),
  ],
  ultimate: defendSkill({
    id: 'yuji-brink-control',
    name: 'Brink Control',
    description: "This skill makes Yuji invulnerable for 1 turn. If Yuji takes any damage while invulnerable, the health he gains after Sukuna's transformation will be increased by 5; this effect stacks.",
    targetRule: 'self',
    classes: ['Strategic', 'Instant', 'Ultimate'],
    cooldown: 4,
    duration: 1,
    energyCost: { mental: 1 },
    effects: [
      { type: 'invulnerable', duration: 1, target: 'self' },
      {
        type: 'addModifier',
        target: 'self',
        modifier: {
          label: 'Brink Control Bonus',
          stat: 'cooldownTick',
          mode: 'flat',
          value: 0,
          duration: { kind: 'rounds', rounds: 1 },
          tags: ['yuji-sukuna-bonus-on-blocked-damage'],
          visible: true,
          stacking: 'replace',
        },
      },
    ],
  }),
})
