export const characters = [
  {
    id: 1,
    name: "Gojo",
    maxHp: 105,
    hp: 105,
    maxMana: 100,
    mana: 100,
    attack: 24,
    defense: 18,
    cursedOutput: 30,
    cursedResistance: 22,
    critChance: 0.05,
    rarity: "UR",
    passive: {
      name: "Six Eyes",
      description: "Cooldowns reduce 1 turn faster, cursed energy costs reduced by 10%",
      type: "cooldown-reduction",
      value: 1,
      manaReduction: 0.10,
    },
    abilities: [
      {
        id: "gojo-1",
        name: "Infinity",
        description: "Raises a cursed barrier for the next enemy turn",
        type: "defensive",
        barrierValue: 60,
        barrierDuration: 1,
        manaCost: 30,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "gojo-2",
        name: "Red - Reversal",
        description: "Deals 34 base damage + 20% cursed output",
        type: "attack",
        damageBase: 34,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        manaCost: 25,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "gojo-3",
        name: "Blue - Lapse",
        description: "Deals 22 base damage + binds for 1 turn",
        type: "attack-stun",
        damageBase: 22,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        bindingDuration: 1,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "gojo-ult",
      name: "Hollow Purple",
      description: "Deals 55 base damage to all enemies",
      type: "attack-all",
      damageBase: 55,
      scaling: 0.2,
      scalingStat: "cursedOutput",
      damageType: "cursed",
      manaCost: 75,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
  {
    id: 2,
    name: "Yuji",
    maxHp: 95,
    hp: 95,
    maxMana: 100,
    mana: 100,
    attack: 22,
    defense: 18,
    cursedOutput: 16,
    cursedResistance: 18,
    critChance: 0.05,
    rarity: "SSR",
    passive: {
      name: "Vessel Body",
      description: "Heals 6 HP at the start of each turn",
      type: "regen",
      value: 6,
    },
    abilities: [
      {
        id: "yuji-1",
        name: "Divergent Fist",
        description: "Deals 30 base damage + 20% Attack",
        type: "attack",
        damageBase: 30,
        scaling: 0.2,
        scalingStat: "attack",
        damageType: "physical",
        manaCost: 20,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "yuji-2",
        name: "Manji Kick",
        description: "Deals 24 base damage + 20% Attack",
        type: "attack",
        damageBase: 24,
        scaling: 0.2,
        scalingStat: "attack",
        damageType: "physical",
        manaCost: 15,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "yuji-3",
        name: "Adrenaline Rush",
        description: "Reinforces Attack by 14 for 2 turns",
        type: "buff",
        buffStat: "attack",
        buffAmount: 14,
        duration: 2,
        manaCost: 30,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "yuji-ult",
      name: "Black Flash",
      description: "Deals 70 base damage + 20% Attack",
      type: "attack",
      damageBase: 70,
      scaling: 0.2,
      scalingStat: "attack",
      damageType: "physical",
      manaCost: 70,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
  {
    id: 3,
    name: "Megumi",
    maxHp: 88,
    hp: 88,
    maxMana: 100,
    mana: 100,
    attack: 19,
    defense: 16,
    cursedOutput: 24,
    cursedResistance: 18,
    critChance: 0.05,
    rarity: "SSR",
    passive: {
      name: "Ten Shadows",
      description: "All attacks deal 10% bonus damage",
      type: "damage-boost",
      value: 0.10,
    },
    abilities: [
      {
        id: "megumi-1",
        name: "Divine Dogs",
        description: "Deals 24 base damage + 20% cursed output",
        type: "attack",
        damageBase: 24,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        manaCost: 20,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "megumi-2",
        name: "Nue",
        description: "Deals 20 base damage + binds for 1 turn",
        type: "attack-stun",
        damageBase: 20,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        bindingDuration: 1,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "megumi-3",
        name: "Toad",
        description: "Heals all allies for 18 HP",
        type: "heal-all",
        healAmount: 18,
        manaCost: 40,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "megumi-ult",
      name: "Chimera Shadow Garden",
      description: "Deals 38 base damage to all enemies and heals allies",
      type: "ultimate-megumi",
      damageBase: 38,
      scaling: 0.2,
      scalingStat: "cursedOutput",
      damageType: "cursed",
      healAmount: 22,
      manaCost: 80,
      cooldown: 6,
      currentCooldown: 0,
    },
  },
  {
    id: 4,
    name: "Nobara",
    maxHp: 82,
    hp: 82,
    maxMana: 100,
    mana: 100,
    attack: 21,
    defense: 15,
    cursedOutput: 22,
    cursedResistance: 16,
    critChance: 0.05,
    rarity: "SR",
    passive: {
      name: "Resonance",
      description: "Attacks have a 20% chance to hit twice",
      type: "double-hit",
      value: 0.20,
    },
    abilities: [
      {
        id: "nobara-1",
        name: "Straw Doll",
        description: "Deals 24 base damage + 20% cursed output",
        type: "attack",
        damageBase: 24,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        manaCost: 20,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "nobara-2",
        name: "Hairpin",
        description: "Deals 32 base damage + 20% cursed output",
        type: "attack",
        damageBase: 32,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        manaCost: 30,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "nobara-3",
        name: "Resonance Link",
        description: "Applies 15% curse amplification for 2 turns",
        type: "debuff-mark",
        damageAmp: 0.15,
        duration: 2,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "nobara-ult",
      name: "Black Flash Hairpin",
      description: "Deals 64 base damage + 20% cursed output",
      type: "attack",
      damageBase: 64,
      scaling: 0.2,
      scalingStat: "cursedOutput",
      damageType: "cursed",
      manaCost: 70,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
  {
    id: 5,
    name: "Nanami",
    maxHp: 98,
    hp: 98,
    maxMana: 100,
    mana: 100,
    attack: 25,
    defense: 20,
    cursedOutput: 12,
    cursedResistance: 18,
    critChance: 0.05,
    rarity: "SSR",
    passive: {
      name: "Ratio Technique",
      description: "Attacks deal 20% bonus damage to enemies below 50% HP",
      type: "execute",
      value: 0.20,
      threshold: 0.5,
    },
    abilities: [
      {
        id: "nanami-1",
        name: "Blunted Blade",
        description: "Deals 26 base damage + 20% Attack",
        type: "attack",
        damageBase: 26,
        scaling: 0.2,
        scalingStat: "attack",
        damageType: "physical",
        manaCost: 20,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "nanami-2",
        name: "Weak Point Strike",
        description: "Deals 38 base damage, +20 if target below 50% HP",
        type: "attack-execute",
        damageBase: 38,
        scaling: 0.2,
        scalingStat: "attack",
        damageType: "physical",
        bonusDamage: 20,
        threshold: 0.5,
        manaCost: 35,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "nanami-3",
        name: "Overtime",
        description: "Reinforces Attack, but costs HP",
        type: "buff-self-damage",
        buffStat: "attack",
        buffAmount: 22,
        duration: 3,
        selfDamage: 8,
        manaCost: 30,
        cooldown: 4,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "nanami-ult",
      name: "Collapse",
      description: "Deals 85 base damage + 20% Attack",
      type: "attack",
      damageBase: 85,
      scaling: 0.2,
      scalingStat: "attack",
      damageType: "physical",
      manaCost: 80,
      cooldown: 6,
      currentCooldown: 0,
    },
  },
  {
    id: 6,
    name: "Jogo",
    maxHp: 78,
    hp: 78,
    maxMana: 100,
    mana: 100,
    attack: 20,
    defense: 14,
    cursedOutput: 26,
    cursedResistance: 18,
    critChance: 0.05,
    rarity: "SR",
    passive: {
      name: "Disaster Flame",
      description: "Attacks inflict Cursed Burn for 6 damage",
      type: "burn",
      value: 6,
    },
    abilities: [
      {
        id: "jogo-1",
        name: "Ember Insects",
        description: "Deals 20 base damage + 20% cursed output",
        type: "attack",
        damageBase: 20,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        manaCost: 15,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "jogo-2",
        name: "Flame Pillar",
        description: "Deals 28 base damage + 20% cursed output",
        type: "attack",
        damageBase: 28,
        scaling: 0.2,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        manaCost: 25,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "jogo-3",
        name: "Coffin of the Iron Mountain",
        description: "Binds a target for 2 turns",
        type: "stun-only",
        bindingDuration: 2,
        manaCost: 45,
        cooldown: 4,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "jogo-ult",
      name: "Maximum Meteor",
      description: "Deals 62 base damage to all enemies",
      type: "attack-all",
      damageBase: 62,
      scaling: 0.2,
      scalingStat: "cursedOutput",
      damageType: "cursed",
      manaCost: 75,
      cooldown: 6,
      currentCooldown: 0,
    },
  },
  {
    id: 7,
    name: "Panda",
    maxHp: 115,
    hp: 115,
    maxMana: 100,
    mana: 100,
    attack: 26,
    defense: 20,
    cursedOutput: 14,
    cursedResistance: 18,
    critChance: 0.05,
    rarity: "SSR",
    passive: {
      name: "Gorilla Core",
      description: "After 3 techniques, awaken Gorilla Core for 2 turns",
      type: "gorilla-core",
    },
    abilities: [
      {
        id: "panda-1",
        name: "Drumming Beat",
        description: "Deals 80 base damage + 120% Attack",
        type: "attack",
        damageBase: 80,
        scaling: 1.2,
        scalingStat: "attack",
        damageType: "physical",
        coreDefenseDebuffPercent: 0.2,
        coreDefenseDebuffDuration: 2,
        manaCost: 30,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "panda-2",
        name: "Charging Tackle",
        description: "Deals 60 base damage + 100% Attack, reinforces Defense",
        type: "attack",
        damageBase: 60,
        scaling: 1.0,
        scalingStat: "attack",
        damageType: "physical",
        selfDefenseBuffPercent: 0.15,
        selfDefenseBuffDuration: 2,
        coreAllEnemies: true,
        manaCost: 40,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "panda-3",
        name: "Sister Core's Embrace",
        description: "Heals self for 20% HP and cleanses one affliction",
        type: "heal-self",
        healPercent: 0.2,
        cleanseDebuff: true,
        resetTechniqueCounter: true,
        manaCost: 50,
        cooldown: 4,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "panda-ult",
      name: "Unblockable Drumming Beat",
      description: "Deals 100 base damage to all enemies (Gorilla Core required)",
      type: "attack-all",
      damageBase: 100,
      scaling: 1.5,
      scalingStat: "attack",
      damageType: "physical",
      requiresGorillaCore: true,
      coreDamageBase: 150,
      coreScaling: 2.0,
      coreBindDuration: 1,
      manaCost: 100,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
  {
    id: 8,
    name: "Toge Inumaki",
    maxHp: 88,
    hp: 88,
    maxMana: 120,
    mana: 120,
    attack: 16,
    defense: 15,
    cursedOutput: 30,
    cursedResistance: 20,
    critChance: 0.05,
    rarity: "SSR",
    passive: {
      name: "Cursed Speech Resonance",
      description: "Cursed Speech techniques apply Speech Mark stacks",
      type: "speech-mark",
    },
    abilities: [
      {
        id: "inumaki-1",
        name: "Don't Move",
        description: "Deals 40 base damage + 80% output and binds",
        type: "attack-stun",
        damageBase: 40,
        scaling: 0.8,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        bindingDuration: 1,
        speechMarkStacks: 1,
        manaCost: 35,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "inumaki-2",
        name: "Get Crushed",
        description: "Deals 70 base damage + 110% output, lowers Attack",
        type: "attack",
        damageBase: 70,
        scaling: 1.1,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        attackDebuffPercent: 0.25,
        attackDebuffDuration: 2,
        speechMarkStacks: 1,
        manaCost: 45,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "inumaki-3",
        name: "Explode",
        description: "Deals 50 base damage to all enemies, marks primary",
        type: "attack-all-primary-mark",
        damageBase: 50,
        scaling: 0.9,
        scalingStat: "cursedOutput",
        damageType: "cursed",
        applySpeechMark: true,
        manaCost: 40,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "inumaki-ult",
      name: "Blast Away",
      description: "Deals 120 base damage and binds all enemies",
      type: "attack-all",
      damageBase: 120,
      scaling: 1.8,
      scalingStat: "cursedOutput",
      damageType: "cursed",
      bindingAllDuration: 1,
      speechMarkAllStacks: 2,
      recoilPercent: 0.1,
      manaCost: 120,
      cooldown: 6,
      currentCooldown: 0,
    },
  },
  {
    id: 9,
    name: "Maki Zen'in",
    maxHp: 100,
    hp: 100,
    maxMana: 80,
    mana: 80,
    attack: 28,
    defense: 22,
    cursedOutput: 10,
    cursedResistance: 16,
    critChance: 0.05,
    rarity: "SSR",
    passive: {
      name: "Heavenly Restriction",
      description: "No natural cursed energy regen, +20% crit chance",
      type: "heavenly-restriction",
      critBonus: 0.2,
    },
    abilities: [
      {
        id: "maki-1",
        name: "Cursed Tool Flurry",
        description: "Deals 50 base damage + 100% Attack",
        type: "attack",
        damageBase: 50,
        scaling: 1.0,
        scalingStat: "attack",
        damageType: "physical",
        isBasic: true,
        onCritCooldownReduction: true,
        manaCost: 25,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "maki-2",
        name: "Precision Thrust",
        description: "Deals 90 base damage + 140% Attack, guaranteed crit",
        type: "attack",
        damageBase: 90,
        scaling: 1.4,
        scalingStat: "attack",
        damageType: "physical",
        guaranteedCrit: true,
        damageAmp: 0.15,
        damageAmpDuration: 2,
        manaCost: 40,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "maki-3",
        name: "Weapon Arsenal",
        description: "Deals 40 base damage to 2 random enemies",
        type: "attack-random",
        damageBase: 40,
        scaling: 0.8,
        scalingStat: "attack",
        damageType: "physical",
        targetCount: 2,
        selfAttackBuffPercent: 0.3,
        selfAttackBuffDuration: 3,
        setNextBasicDouble: true,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "maki-ult",
      name: "Three-Section Staff Maelstrom",
      description: "Deals 110 base damage to all enemies",
      type: "attack-all",
      damageBase: 110,
      scaling: 1.7,
      scalingStat: "attack",
      damageType: "physical",
      energyRestorePerHit: 15,
      grantFlowStateTurns: 3,
      manaCost: 80,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
]
