export const characters = [
  {
    id: 1,
    name: "Gojo",
    maxHp: 105,
    hp: 105,
    maxMana: 100,
    mana: 100,
    attack: 24,
    rarity: "UR",
    passive: {
      name: "Six Eyes",
      description: "Cooldowns reduce 1 turn faster, mana costs reduced by 10%",
      type: "cooldown-reduction",
      value: 1,
      manaReduction: 0.10,
    },
    abilities: [
      {
        id: "gojo-1",
        name: "Infinity",
        description: "Become invincible for the next enemy turn",
        type: "defensive",
        manaCost: 30,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "gojo-2",
        name: "Red - Reversal",
        description: "Deals 34 damage to one enemy",
        type: "attack",
        damage: 34,
        manaCost: 25,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "gojo-3",
        name: "Blue - Lapse",
        description: "Deals 22 damage and stuns for 1 turn",
        type: "attack-stun",
        damage: 22,
        stunDuration: 1,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "gojo-ult",
      name: "Hollow Purple",
      description: "Deals 55 damage to all enemies",
      type: "attack-all",
      damage: 55,
      manaCost: 75,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
  {
    id: 2,
    name: "Yuji",
    maxHp: 95,
    hp: 95,
    maxMana: 100,
    mana: 100,
    attack: 22,
    rarity: "SSR",
    passive: {
      name: "Vessel Body",
      description: "Heals 6 HP at the start of each turn",
      type: "regen",
      value: 6,
    },
    abilities: [
      {
        id: "yuji-1",
        name: "Divergent Fist",
        description: "Deals 30 damage to one enemy",
        type: "attack",
        damage: 30,
        manaCost: 20,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "yuji-2",
        name: "Manji Kick",
        description: "Deals 24 damage to one enemy",
        type: "attack",
        damage: 24,
        manaCost: 15,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "yuji-3",
        name: "Adrenaline Rush",
        description: "Boosts own attack by 14 for 2 turns",
        type: "buff",
        buffAmount: 14,
        duration: 2,
        manaCost: 30,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "yuji-ult",
      name: "Black Flash",
      description: "Deals 70 damage to one enemy",
      type: "attack",
      damage: 70,
      manaCost: 70,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
  {
    id: 3,
    name: "Megumi",
    maxHp: 88,
    hp: 88,
    maxMana: 100,
    mana: 100,
    attack: 19,
    rarity: "SSR",
    passive: {
      name: "Ten Shadows",
      description: "All attacks deal 10% bonus damage",
      type: "damage-boost",
      value: 0.10,
    },
    abilities: [
      {
        id: "megumi-1",
        name: "Divine Dogs",
        description: "Deals 24 damage to one enemy",
        type: "attack",
        damage: 24,
        manaCost: 20,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "megumi-2",
        name: "Nue",
        description: "Deals 20 damage and stuns for 1 turn",
        type: "attack-stun",
        damage: 20,
        stunDuration: 1,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "megumi-3",
        name: "Toad",
        description: "Heals all allies for 18 HP",
        type: "heal-all",
        healAmount: 18,
        manaCost: 40,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "megumi-ult",
      name: "Chimera Shadow Garden",
      description: "Deals 38 damage to all enemies and heals allies for 22",
      type: "ultimate-megumi",
      damage: 38,
      healAmount: 22,
      manaCost: 80,
      cooldown: 6,
      currentCooldown: 0,
    },
  },
  {
    id: 4,
    name: "Nobara",
    maxHp: 82,
    hp: 82,
    maxMana: 100,
    mana: 100,
    attack: 21,
    rarity: "SR",
    passive: {
      name: "Resonance",
      description: "Attacks have a 20% chance to hit twice",
      type: "double-hit",
      value: 0.20,
    },
    abilities: [
      {
        id: "nobara-1",
        name: "Straw Doll",
        description: "Deals 24 damage to one enemy",
        type: "attack",
        damage: 24,
        manaCost: 20,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "nobara-2",
        name: "Hairpin",
        description: "Deals 32 damage to one enemy",
        type: "attack",
        damage: 32,
        manaCost: 30,
        cooldown: 3,
        currentCooldown: 0,
      },
      {
        id: "nobara-3",
        name: "Resonance Link",
        description: "Marks an enemy to take +14 damage for 2 turns",
        type: "debuff-mark",
        extraDamage: 14,
        duration: 2,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "nobara-ult",
      name: "Black Flash Hairpin",
      description: "Deals 64 damage to one enemy",
      type: "attack",
      damage: 64,
      manaCost: 70,
      cooldown: 5,
      currentCooldown: 0,
    },
  },
  {
    id: 5,
    name: "Nanami",
    maxHp: 98,
    hp: 98,
    maxMana: 100,
    mana: 100,
    attack: 25,
    rarity: "SSR",
    passive: {
      name: "Ratio Technique",
      description: "Attacks deal 20% bonus damage to enemies below 50% HP",
      type: "execute",
      value: 0.20,
      threshold: 0.5,
    },
    abilities: [
      {
        id: "nanami-1",
        name: "Blunted Blade",
        description: "Deals 26 damage to one enemy",
        type: "attack",
        damage: 26,
        manaCost: 20,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "nanami-2",
        name: "Weak Point Strike",
        description: "Deals 38 damage, +20 if enemy below 50% HP",
        type: "attack-execute",
        damage: 38,
        bonusDamage: 20,
        threshold: 0.5,
        manaCost: 35,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "nanami-3",
        name: "Overtime",
        description: "Boosts own attack by 22 but takes 8 damage",
        type: "buff-self-damage",
        buffAmount: 22,
        selfDamage: 8,
        duration: 3,
        manaCost: 30,
        cooldown: 4,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "nanami-ult",
      name: "Collapse",
      description: "Deals 85 damage to one enemy",
      type: "attack",
      damage: 85,
      manaCost: 80,
      cooldown: 6,
      currentCooldown: 0,
    },
  },
  {
    id: 6,
    name: "Jogo",
    maxHp: 78,
    hp: 78,
    maxMana: 100,
    mana: 100,
    attack: 20,
    rarity: "SR",
    passive: {
      name: "Disaster Flame",
      description: "Attacks burn enemies for 6 damage at turn start",
      type: "burn",
      value: 6,
    },
    abilities: [
      {
        id: "jogo-1",
        name: "Ember Insects",
        description: "Deals 20 damage to one enemy",
        type: "attack",
        damage: 20,
        manaCost: 15,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: "jogo-2",
        name: "Flame Pillar",
        description: "Deals 28 damage to one enemy",
        type: "attack",
        damage: 28,
        manaCost: 25,
        cooldown: 2,
        currentCooldown: 0,
      },
      {
        id: "jogo-3",
        name: "Coffin of the Iron Mountain",
        description: "Stuns one enemy for 2 turns",
        type: "stun-only",
        stunDuration: 2,
        manaCost: 45,
        cooldown: 4,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: "jogo-ult",
      name: "Maximum Meteor",
      description: "Deals 62 damage to all enemies",
      type: "attack-all",
      damage: 62,
      manaCost: 75,
      cooldown: 6,
      currentCooldown: 0,
    },
  },
]
