export const characters = [
    {
      id: 1,
      name: "Gojo",
      maxHp: 100,
      hp: 100,
      attack: 25,
      rarity: "UR",
      passive: {
        name: "Six Eyes",
        description: "Cooldowns reduce 1 turn faster",
        type: "cooldown-reduction",
        value: 1,
      },
      abilities: [
        {
          id: "gojo-1",
          name: "Infinity",
          description: "Blocks all damage next enemy turn",
          type: "defensive",
          cooldown: 3,
          currentCooldown: 0,
        },
        {
          id: "gojo-2",
          name: "Red - Reversal",
          description: "Deals 35 damage to one enemy",
          type: "attack",
          damage: 35,
          cooldown: 2,
          currentCooldown: 0,
        },
        {
          id: "gojo-3",
          name: "Blue - Lapse",
          description: "Deals 25 damage and pulls enemy (stun 1 turn)",
          type: "attack-stun",
          damage: 25,
          stunDuration: 1,
          cooldown: 3,
          currentCooldown: 0,
        },
      ],
      ultimate: {
        id: "gojo-ult",
        name: "Hollow Purple",
        description: "Deals 60 damage to ALL enemies",
        type: "attack-all",
        damage: 60,
        cooldown: 5,
        currentCooldown: 0,
      },
    },
    {
      id: 2,
      name: "Yuji",
      maxHp: 90,
      hp: 90,
      attack: 20,
      rarity: "SSR",
      passive: {
        name: "Vessel Body",
        description: "Heals 5 HP at the start of each turn",
        type: "regen",
        value: 5,
      },
      abilities: [
        {
          id: "yuji-1",
          name: "Divergent Fist",
          description: "Deals 30 damage with delayed impact",
          type: "attack",
          damage: 30,
          cooldown: 2,
          currentCooldown: 0,
        },
        {
          id: "yuji-2",
          name: "Manji Kick",
          description: "Deals 20 damage, ignores defense buffs",
          type: "attack",
          damage: 20,
          cooldown: 1,
          currentCooldown: 0,
        },
        {
          id: "yuji-3",
          name: "Rage Mode",
          description: "Boosts own attack by 15 for 2 turns",
          type: "buff",
          buffAmount: 15,
          duration: 2,
          cooldown: 3,
          currentCooldown: 0,
        },
      ],
      ultimate: {
        id: "yuji-ult",
        name: "Black Flash",
        description: "Deals 70 critical damage to one enemy",
        type: "attack",
        damage: 70,
        cooldown: 5,
        currentCooldown: 0,
      },
    },
    {
      id: 3,
      name: "Megumi",
      maxHp: 85,
      hp: 85,
      attack: 18,
      rarity: "SSR",
      passive: {
        name: "Ten Shadows",
        description: "Summons deal 10% bonus damage",
        type: "damage-boost",
        value: 0.10,
      },
      abilities: [
        {
          id: "megumi-1",
          name: "Divine Dogs",
          description: "Deals 25 damage to one enemy",
          type: "attack",
          damage: 25,
          cooldown: 1,
          currentCooldown: 0,
        },
        {
          id: "megumi-2",
          name: "Nue",
          description: "Deals 20 damage and stuns for 1 turn",
          type: "attack-stun",
          damage: 20,
          stunDuration: 1,
          cooldown: 3,
          currentCooldown: 0,
        },
        {
          id: "megumi-3",
          name: "Toad",
          description: "Heals all allies for 20 HP",
          type: "heal-all",
          healAmount: 20,
          cooldown: 3,
          currentCooldown: 0,
        },
      ],
      ultimate: {
        id: "megumi-ult",
        name: "Chimera Shadow Garden",
        description: "Deals 40 damage to all enemies and heals team for 25",
        type: "ultimate-megumi",
        damage: 40,
        healAmount: 25,
        cooldown: 6,
        currentCooldown: 0,
      },
    },
    {
      id: 4,
      name: "Sukuna",
      maxHp: 120,
      hp: 120,
      attack: 30,
      rarity: "UR",
      passive: {
        name: "King of Curses",
        description: "All attacks deal 15% bonus damage",
        type: "damage-boost",
        value: 0.15,
      },
      abilities: [
        {
          id: "sukuna-1",
          name: "Dismantle",
          description: "Deals 40 damage to one enemy",
          type: "attack",
          damage: 40,
          cooldown: 2,
          currentCooldown: 0,
        },
        {
          id: "sukuna-2",
          name: "Cleave",
          description: "Deals 25 damage to ALL enemies",
          type: "attack-all",
          damage: 25,
          cooldown: 3,
          currentCooldown: 0,
        },
        {
          id: "sukuna-3",
          name: "Reverse Cursed Technique",
          description: "Heals self for 35 HP",
          type: "heal-self",
          healAmount: 35,
          cooldown: 4,
          currentCooldown: 0,
        },
      ],
      ultimate: {
        id: "sukuna-ult",
        name: "Malevolent Shrine",
        description: "Deals 80 damage to ALL enemies",
        type: "attack-all",
        damage: 80,
        cooldown: 6,
        currentCooldown: 0,
      },
    },
    {
      id: 5,
      name: "Mahito",
      maxHp: 80,
      hp: 80,
      attack: 22,
      rarity: "SR",
      passive: {
        name: "Soul Shape",
        description: "25% chance to dodge attacks",
        type: "dodge-chance",
        value: 0.25,
      },
      abilities: [
        {
          id: "mahito-1",
          name: "Idle Transfiguration",
          description: "Deals 28 damage to one enemy",
          type: "attack",
          damage: 28,
          cooldown: 2,
          currentCooldown: 0,
        },
        {
          id: "mahito-2",
          name: "Body Distortion",
          description: "Heals self for 25 HP",
          type: "heal-self",
          healAmount: 25,
          cooldown: 3,
          currentCooldown: 0,
        },
        {
          id: "mahito-3",
          name: "Soul Multiplicity",
          description: "Deals 15 damage to all enemies",
          type: "attack-all",
          damage: 15,
          cooldown: 2,
          currentCooldown: 0,
        },
      ],
      ultimate: {
        id: "mahito-ult",
        name: "Instant Spirit Body of Distorted Killing",
        description: "Become invincible and deal 50 damage to one enemy",
        type: "ultimate-mahito",
        damage: 50,
        cooldown: 5,
        currentCooldown: 0,
      },
    },
    {
      id: 6,
      name: "Jogo",
      maxHp: 75,
      hp: 75,
      attack: 19,
      rarity: "SR",
      passive: {
        name: "Disaster Flame",
        description: "Attacks burn enemies for 5 damage over time",
        type: "burn",
        value: 5,
      },
      abilities: [
        {
          id: "jogo-1",
          name: "Ember Insects",
          description: "Deals 22 damage to one enemy",
          type: "attack",
          damage: 22,
          cooldown: 1,
          currentCooldown: 0,
        },
        {
          id: "jogo-2",
          name: "Flame Pillar",
          description: "Deals 30 damage to one enemy",
          type: "attack",
          damage: 30,
          cooldown: 2,
          currentCooldown: 0,
        },
        {
          id: "jogo-3",
          name: "Coffin of the Iron Mountain",
          description: "Stuns one enemy for 2 turns",
          type: "stun-only",
          stunDuration: 2,
          cooldown: 4,
          currentCooldown: 0,
        },
      ],
      ultimate: {
        id: "jogo-ult",
        name: "Maximum Meteor",
        description: "Deals 70 damage to ALL enemies",
        type: "attack-all",
        damage: 70,
        cooldown: 6,
        currentCooldown: 0,
      },
    },
  ]