export const storyEnemies = {
  'fly-head': {
    id: 'fly-head',
    name: 'Fly Head Curse',
    maxHp: 55,
    hp: 55,
    maxMana: 60,
    mana: 60,
    attack: 14,
    rarity: 'SR',
    passive: {
      name: 'Cursed Instinct',
      description: 'Attacks deal 10% bonus damage.',
      type: 'damage-boost',
      value: 0.1,
    },
    abilities: [
      {
        id: 'fly-head-1',
        name: 'Claw Swipe',
        description: 'Deals 18 damage to one enemy.',
        type: 'attack',
        damage: 18,
        manaCost: 15,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: 'fly-head-2',
        name: 'Shriek',
        description: 'Deals 12 damage and stuns for 1 turn.',
        type: 'attack-stun',
        damage: 12,
        stunDuration: 1,
        manaCost: 20,
        cooldown: 2,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: 'fly-head-ult',
      name: 'Swarm Rush',
      description: 'Deals 20 damage to all enemies.',
      type: 'attack-all',
      damage: 20,
      manaCost: 35,
      cooldown: 4,
      currentCooldown: 0,
    },
  },
  'finger-bearer': {
    id: 'finger-bearer',
    name: 'Finger Bearer',
    maxHp: 220,
    hp: 220,
    maxMana: 120,
    mana: 120,
    attack: 26,
    rarity: 'SSR',
    passive: {
      name: 'Cursed Giant',
      description: 'Attacks deal +4 bonus damage.',
      type: 'stacking-attack',
      value: 4,
    },
    abilities: [
      {
        id: 'finger-bearer-1',
        name: 'Crushing Slam',
        description: 'Deals 28 damage to one enemy.',
        type: 'attack',
        damage: 28,
        manaCost: 20,
        cooldown: 1,
        currentCooldown: 0,
      },
      {
        id: 'finger-bearer-2',
        name: 'Malice Burst',
        description: 'Deals 20 damage and stuns for 1 turn.',
        type: 'attack-stun',
        damage: 20,
        stunDuration: 1,
        manaCost: 35,
        cooldown: 3,
        currentCooldown: 0,
      },
    ],
    ultimate: {
      id: 'finger-bearer-ult',
      name: 'Cursed Howl',
      description: 'Deals 30 damage to all enemies.',
      type: 'attack-all',
      damage: 30,
      manaCost: 60,
      cooldown: 4,
      currentCooldown: 0,
    },
  },
}

export const storyChapters = [
  {
    id: 'chapter-1',
    title: 'Chapter 1 — The Vessel',
    subtitle: 'Sugisawa High Incident',
    nodes: [
      {
        id: '1-1',
        title: 'Last Words',
        type: 'story',
        location: 'Sugisawa Hospital — Evening',
        system: 'Some promises are harder to keep than others.',
        lines: [
          { speaker: 'Grandpa Itadori', text: 'Yuji... come closer.' },
          { speaker: 'Yuji Itadori', text: 'Save your strength, old man. The doctor said—' },
          { speaker: 'Grandpa Itadori', text: "Forget what he said. I'm dying. And I need to tell you something." },
          { speaker: 'Grandpa Itadori', text: "You're strong, Yuji. Stronger than you know. But strength alone won't save you." },
          { speaker: 'Yuji Itadori', text: 'What are you talking about?' },
          { speaker: 'Grandpa Itadori', text: "When I'm gone... don't be alone. Find people. Protect them." },
          { speaker: 'Grandpa Itadori', text: 'And when your time comes... die surrounded by others. Not like me. Promise me.' },
          { speaker: 'Yuji Itadori', text: '...I promise.' },
        ],
      },
      {
        id: '1-2',
        title: 'The Occult Club',
        type: 'story',
        location: 'Sugisawa High School — Night',
        system: 'Cursed energy attracts curses. The finger has been unsealed.',
        lines: [
          { speaker: 'Sasaki', text: "Itadori! Finally! We've been waiting for you!" },
          { speaker: 'Iguchi', text: "Dude, you gotta see what we found. This is the real deal." },
          { speaker: 'Yuji Itadori', text: 'Wait. You removed the seals?' },
          { speaker: 'Yuji Itadori', text: "...Something's wrong." },
          { speaker: 'Iguchi', text: 'What the hell was that?!' },
          { speaker: 'Yuji Itadori', text: 'Both of you. Get behind me. Now.' },
        ],
      },
      {
        id: '1-3',
        title: 'First Contact',
        type: 'battle',
        location: 'Sugisawa High School — Hallway',
        intro: [
          'A grotesque curse lunges from the shadows.',
          'Yuji shoves his friends aside and braces for impact.',
        ],
        battle: {
          mode: 'Tutorial Battle',
          playerIds: ['Yuji'],
          enemyIds: ['fly-head', 'fly-head'],
          objective: 'Defeat all enemies.',
          prompts: [
            'Tap an ability to queue it for this turn.',
            'Abilities have mana costs. Manage your energy carefully.',
            'End your turn when you have selected your actions.',
          ],
        },
      },
      {
        id: '1-4',
        title: 'Cornered',
        type: 'battle',
        location: 'Sugisawa High School — Third Floor',
        intro: [
          'Megumi calls out Divine Dogs as the Finger Bearer emerges.',
          'This is a holding action. Survive.',
        ],
        battle: {
          mode: 'Story Battle',
          playerIds: ['Megumi'],
          enemyIds: ['finger-bearer'],
          objective: 'Survive 4 turns.',
          type: 'survival',
          turnLimit: 4,
          enemyCannotDie: true,
          prompts: [
            'Some battles require survival, not victory.',
            "Use defensive abilities to reduce incoming damage.",
            "Megumi's Divine Dogs can attack and intercept.",
          ],
        },
        outro: [
          'Megumi is thrown against the wall. His shikigami flicker.',
          'A voice calls out from the doorway: "HEY! UGLY!"',
        ],
      },
      {
        id: '1-5',
        title: 'The King of Curses',
        type: 'battle',
        location: 'Sugisawa High School — Rooftop',
        intro: [
          'Yuji has nowhere left to run. The finger pulses in his hand.',
          'He swallows it. Power surges.',
        ],
        battle: {
          mode: 'Boss Battle',
          playerIds: ['Yuji'],
          enemyIds: ['finger-bearer'],
          objective: 'Defeat the Finger Bearer.',
          type: 'boss',
          playerBuffs: {
            Yuji: { hpBonus: 30, manaBonus: 20, attackBonus: 6 },
          },
          unlocks: ['Divergent Fist'],
        },
        outro: [
          'The Finger Bearer dissolves into cursed mist.',
          'Megumi stares, stunned. "You became Sukuna’s vessel."',
          'Yuji exhales. "Apparently."',
          'Megumi nods. "Come with me. There’s someone you need to meet."',
        ],
      },
    ],
    rewards: [
      { type: 'character', label: 'Yuji Itadori — Playable Character' },
      { type: 'character', label: 'Megumi Fushiguro — Playable Character' },
      { type: 'soft_currency', label: 'Cursed Energy x500', amount: 500 },
      { type: 'premium_currency', label: 'Premium Currency x100', amount: 100 },
      { type: 'item', label: 'Finger Fragment x3 (Gacha Material)' },
      { type: 'title', label: 'Title: "The Vessel"' },
    ],
    preview: [
      'Gojo Satoru: "So you’re the kid who ate Sukuna’s finger and lived? Interesting."',
      'Chapter 2: Execution — Coming Soon',
    ],
  },
]
